# -*- coding: utf-8 -*-
"""21pt40_math_modelling_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTJZt2GmAfRkW9O2nmguYyl2mWT4jP6W
"""

#Problem 1
import numpy as np
import matplotlib.pyplot as plt

def simulate_system(a0, r, steps):
    a = [a0]
    for n in range(steps):
        a.append((r**n) * a[-1])
    return a

np.random.seed(42)

examples_per_case = 5

case_definitions = [
    ("i) r = 0", lambda: 0),
    ("ii) 0 < r < 1", lambda: np.random.uniform(0.01, 0.99)),
    ("iii) -1 < r < 0", lambda: np.random.uniform(-0.99, -0.01)),
    ("iv) r > 1", lambda: 1 + np.random.uniform(0.01, 2)),
    ("v) r < -1", lambda: -1 - np.random.uniform(0.01, 2))
]

fig, axes = plt.subplots(len(case_definitions), 1, figsize=(12, 18))
if len(case_definitions) == 1:
    axes = [axes]

a0 = 0.5
min_steps = 100
max_steps = 200

for ax, (case_name, r_generator) in zip(axes, case_definitions):
    for _ in range(examples_per_case):
        r = r_generator()
        steps = np.random.randint(min_steps, max_steps)
        trajectory = simulate_system(a0, r, steps)
        ax.plot(trajectory, 'o-', markersize=3,
                label=f"r={r:.3f}, steps={steps}")

    ax.set_title(case_name)
    ax.set_xlabel('Time step (n)')
    ax.set_ylabel('State ($a_n$)')
    ax.legend()
    ax.grid(True)
    ax.axhline(0, color='black', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.suptitle('Dynamical System: $a_{n+1} = r^n a_n$ - Multiple Random Examples per Case',
             y=1.02, fontsize=14)
plt.show()

#Problem 2
import numpy as np
import matplotlib.pyplot as plt

def simulate_digoxin(initial_concentration, dosage, days):
    concentrations = [initial_concentration]
    for _ in range(days):
        new_concentration = 0.5 * concentrations[-1] + dosage
        concentrations.append(new_concentration)
    return concentrations

days = 10
initial_concentration = 0
dosages = [0.1, 0.2, 0.3]

plt.figure(figsize=(10, 6))
for D in dosages:
    C = simulate_digoxin(initial_concentration, D, days)
    plt.plot(C, 'o-', label=f'Dosage D={D} mg')
    plt.axhline(y=2*D, color='gray', linestyle='--', alpha=0.5)

plt.title('Digoxin Concentration Over Time')
plt.xlabel('Days')
plt.ylabel('Concentration (mg)')
plt.legend()
plt.grid(True)
plt.show()

#Problem 3
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import triang

params = {
    'uniform': {'low': 0, 'high': 10},
    'exponential': {'scale': 1.0},
    'weibull': {'a': 1.5, 'scale': 1.0},
    'triangular': {'c': 0.7, 'loc': 0, 'scale': 10}
}

sample_sizes = [500, 1000, 10000, 100000]

fig, axes = plt.subplots(4, 4, figsize=(20, 16))
plt.subplots_adjust(hspace=0.5, wspace=0.3)

for i, dist in enumerate(['uniform', 'exponential', 'weibull', 'triangular']):
    for j, size in enumerate(sample_sizes):
        ax = axes[i, j]

        if dist == 'uniform':
            data = np.random.uniform(low=params[dist]['low'], high=params[dist]['high'], size=size)
        elif dist == 'exponential':
            data = np.random.exponential(scale=params[dist]['scale'], size=size)
        elif dist == 'weibull':
            data = np.random.weibull(a=params[dist]['a'], size=size) * params[dist]['scale']
        elif dist == 'triangular':
            data = np.random.triangular(left=params[dist]['loc'],
                                      mode=params[dist]['loc'] + params[dist]['c']*params[dist]['scale'],
                                      right=params[dist]['loc'] + params[dist]['scale'],
                                      size=size)

        n, bins, patches = ax.hist(data, bins=30, density=True, alpha=0.6, color='skyblue', edgecolor='black')

        bin_centers = (bins[:-1] + bins[1:]) / 2
        ax.plot(bin_centers, n, 'r-', linewidth=2)

        ax.set_title(f'{dist.capitalize()} (n={size})')
        ax.set_xlabel('Value')
        ax.set_ylabel('Density')
        ax.grid(True, alpha=0.3)

plt.suptitle('Random Number Distributions with Histograms and Frequency Polygons', y=1.02, fontsize=16)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def estimate_pi(num_samples):
    x = np.random.uniform(0, 1, num_samples)
    y = np.random.uniform(0, 1, num_samples)

    distances = np.sqrt(x**2 + y**2)

    inside = np.sum(distances <= 1)

    pi_estimate = 4 * inside / num_samples
    return pi_estimate, x, y, distances

num_samples = 1000000

pi_est, x, y, distances = estimate_pi(num_samples)

plt.figure(figsize=(8, 8))
plt.scatter(x[distances <= 1], y[distances <= 1], color='blue', s=1, alpha=0.5, label='Inside circle')
plt.scatter(x[distances > 1], y[distances > 1], color='red', s=1, alpha=0.5, label='Outside circle')
plt.title(f'Monte Carlo Estimation of π: {pi_est:.5f} (True π = {np.pi:.5f})')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.axis('equal')
plt.grid(True)
plt.show()

print(f"Estimated π: {pi_est:.5f}")
print(f"Actual π: {np.pi:.5f}")
print(f"Error: {abs(pi_est - np.pi):.5f} ({abs(pi_est - np.pi)/np.pi*100:.2f}%)")

import numpy as np
import matplotlib.pyplot as plt


BUY_PRICE = 0.30
SELL_PRICE = 0.45
SCRAP_PRICE = 0.05
NEWSPAPERS_BOUGHT = 60
DAY_TYPES = ['Good', 'Fair', 'Poor']
DAY_PROBABILITIES = [0.35, 0.45, 0.20]
DAY_RANGES = [(1, 35), (36, 80), (81, 100)]

DEMAND_VALUES = [40, 50, 60, 70, 80, 90, 100]
GOOD_RANGES = [(1, 3), (4, 8), (9, 23), (24, 43), (44, 78), (79, 93), (94, 100)]
FAIR_RANGES = [(1, 10), (11, 28), (29, 68), (69, 88), (89, 96), (97, 100)]
POOR_RANGES = [(1, 44), (45, 66), (67, 82), (83, 94), (95, 100)]

def get_day_type(random_num):
    for i, (start, end) in enumerate(DAY_RANGES):
        if start <= random_num <= end:
            return DAY_TYPES[i]
    return DAY_TYPES[-1]

def get_demand(day_type, random_num):
    ranges = GOOD_RANGES if day_type == 'Good' else FAIR_RANGES if day_type == 'Fair' else POOR_RANGES
    for i, (start, end) in enumerate(ranges):
        if start <= random_num <= end:
            return DEMAND_VALUES[i]
    return DEMAND_VALUES[-1]

def calculate_financials(demand, newspapers_bought):
    newspapers_sold = min(demand, newspapers_bought)

    revenue = newspapers_sold * SELL_PRICE

    excess_demand = max(0, demand - newspapers_bought)
    loss_excess = excess_demand * (SELL_PRICE - BUY_PRICE)

    unsold = max(0, newspapers_bought - demand)
    salvage = unsold * SCRAP_PRICE

    cost = newspapers_bought * BUY_PRICE
    profit = revenue + salvage - cost

    return revenue, loss_excess, salvage, profit

def run_simulation(num_days):
    np.random.seed(42)
    news_types = []
    demands = []
    revenues = []
    losses = []
    salvages = []
    profits = []

    for day in range(num_days):
        day_random = np.random.randint(1, 101)
        day_type = get_day_type(day_random)
        news_types.append(day_type)

        if day_type == 'Good':
            demand_random = int(np.random.exponential(scale=40)) % 100 + 1
        elif day_type == 'Fair':
            demand_random = int(np.clip(np.random.normal(loc=50, scale=10), 0, 100)) + 1
        else:
            demand_random = int(np.random.poisson(lam=50)) % 100 + 1

        demand = get_demand(day_type, demand_random)
        demands.append(demand)

        revenue, loss_excess, salvage, profit = calculate_financials(demand, NEWSPAPERS_BOUGHT)

        revenues.append(revenue)
        losses.append(loss_excess)
        salvages.append(salvage)
        profits.append(profit)

    avg_revenue = np.mean(revenues)
    avg_loss = np.mean(losses)
    avg_salvage = np.mean(salvages)
    avg_profit = np.mean(profits)

    return {
        'news_types': news_types,
        'demands': demands,
        'revenues': revenues,
        'losses': losses,
        'salvages': salvages,
        'profits': profits,
        'avg_revenue': avg_revenue,
        'avg_loss': avg_loss,
        'avg_salvage': avg_salvage,
        'avg_profit': avg_profit
    }

def main():
    """Run simulations for different day counts and display results."""
    day_counts = [200, 500, 1000, 10000]

    for days in day_counts:
        print(f"\nSimulation for {days} days:")
        results = run_simulation(days)
        print(f"Average Revenue: ${results['avg_revenue']:.2f}")
        print(f"Average Loss from Excess Demand: ${results['avg_loss']:.2f}")
        print(f"Average Salvage from Scrap: ${results['avg_salvage']:.2f}")
        print(f"Average Daily Profit: ${results['avg_profit']:.2f}")

        plt.figure(figsize=(10, 6))
        plt.plot(range(1, days + 1), results['profits'], label='Daily Profit', color='#1f77b4')
        plt.title(f'Daily Profit over {days} Days')
        plt.xlabel('Day')
        plt.ylabel('Profit ($)')
        plt.legend()
        plt.grid(True)
        plt.show()

    np.random.seed(42)
    random_news = np.random.randint(1, 101, size=100)
    news_types_100 = [get_day_type(num) for num in random_news]
    print("\n100 Random News Types (Part a):")
    print(news_types_100)

    np.random.seed(42)
    good_demands = np.random.exponential(scale=40, size=100).astype(int)
    good_demands = np.clip(good_demands, 0, 100)
    fair_demands = np.random.normal(loc=50, scale=10, size=100).astype(int)
    fair_demands = np.clip(fair_demands, 0, 100)
    poor_demands = np.random.poisson(lam=50, size=100)
    poor_demands = np.clip(poor_demands, 0, 100)

    print("\nGood News Demands (Exponential, mean=40, Part b):")
    print(good_demands)
    print("\nFair News Demands (Normal, mean=50, sd=10, Part b):")
    print(fair_demands)
    print("\nPoor News Demands (Poisson, mean=50, Part b):")
    print(poor_demands)

if __name__ == "__main__":
    main()

import numpy as np
import matplotlib.pyplot as plt
from collections import deque

SIM_TIME = 1000
MEAN_INTER_ARRIVAL = 10
SERVICE_MIN = 8
SERVICE_MAX = 12
SERVICE_MEAN = 10

np.random.seed(42)

ARRIVAL = 'arrival'
DEPARTURE = 'departure'

event_queue = []
queue = deque()
system_state = []
wait_times = []
server_busy = False
server_busy_time = 0
current_time = 0
customer_id = 0
num_in_system = 0

inter_arrival = np.random.exponential(MEAN_INTER_ARRIVAL)
event_queue.append((inter_arrival, ARRIVAL, customer_id))
arrival_times = {}

while event_queue and current_time < SIM_TIME:
    event_queue.sort()
    time, event_type, cid = event_queue.pop(0)
    current_time = time

    if event_type == ARRIVAL:
        arrival_times[cid] = current_time
        num_in_system += 1
        system_state.append((current_time, num_in_system))

        if current_time < SIM_TIME:
            next_customer_id = customer_id + 1
            next_arrival_time = current_time + np.random.exponential(MEAN_INTER_ARRIVAL)
            event_queue.append((next_arrival_time, ARRIVAL, next_customer_id))
            customer_id += 1

        if not server_busy:
            server_busy = True
            service_time = np.random.poisson(SERVICE_MEAN)
            service_time = max(SERVICE_MIN, min(SERVICE_MAX, service_time))
            server_busy_time += service_time
            wait_times.append(0)
            event_queue.append((current_time + service_time, DEPARTURE, cid))
        else:
            queue.append(cid)

    elif event_type == DEPARTURE:
        num_in_system -= 1
        system_state.append((current_time, num_in_system))
        service_start = arrival_times[cid] if cid not in queue else current_time - service_time
        wait_time = service_start - arrival_times[cid]
        if wait_time > 0:
            wait_times[-1] = wait_time
        del arrival_times[cid]

        if queue:
            next_cid = queue.popleft()
            service_time = np.random.poisson(SERVICE_MEAN)
            service_time = max(SERVICE_MIN, min(SERVICE_MAX, service_time))
            server_busy_time += service_time
            wait_times.append(current_time - arrival_times[next_cid])
            event_queue.append((current_time + service_time, DEPARTURE, next_cid))
        else:
            server_busy = False

avg_wait_time = np.mean(wait_times) if wait_times else 0
avg_queue_length = sum(wt * len(queue) for wt in wait_times) / SIM_TIME if wait_times else 0
utilization = server_busy_time / SIM_TIME if SIM_TIME > 0 else 0

print(f"Average waiting time in queue: {avg_wait_time:.2f} minutes")
print(f"Average number of customers in queue: {avg_queue_length:.2f}")
print(f"Average utilization of booking station: {utilization:.2%}")

times, counts = zip(*system_state)
plt.step(times, counts, where='post')
plt.xlabel('Time (minutes)')
plt.ylabel('Number of Customers in System')
plt.title('Sample Path of Queueing System')
plt.grid(True)
plt.show()