# -*- coding: utf-8 -*-
"""21pt28_MM_PS3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXcyo4KuyeQCSwGOrnVmKmeMVIdjnmXt
"""

#Q1)

import numpy as np
import matplotlib.pyplot as plt

N_values = [2, 4, 6, 8, 12, 20]

x = np.linspace(-1, 1, 400)

def divided_diff(x, y):
    n = len(y)
    coef = y.copy()
    for j in range(1, n):
        for i in range(n-1, j-1, -1):
            coef[i] = (coef[i] - coef[i-1]) / (x[i] - x[i-j])
    return coef

def newton_poly(x, x_points, coef):
    n = len(x_points) - 1
    result = coef[n]
    for i in range(n-1, -1, -1):
        result = result * (x - x_points[i]) + coef[i]
    return result

# Function to construct p_2N(x) using Newton's divided difference

def construct_p2N(N):
    x_points = [0] + [j/N for j in range(1, N+1)] + [-j/N for j in range(1, N+1)]
    y_points = [1] + [0] * (2 * N)  # p(0) = 1, others = 0
    coef = divided_diff(x_points, y_points)
    return lambda x: newton_poly(x, x_points, coef)

# Plot for each N
for N in N_values:
    p2N = construct_p2N(N)
    plt.plot(x, [p2N(xi) for xi in x], label=f'N = {N}', color='purple')

    plt.xlabel('x')
    plt.ylabel('p_2N(x)')
    plt.title('Polynomial Interpolation for N = {0}'.format(N))
    plt.legend()
    plt.grid(True)
    plt.show()
    print("\n")

print("\n\n")
print("Interpretation:\n")
print("As N increases, the polynomial p_2N(x) exhibits more pronounced oscillations, \nparticularly near the endpoints x = ±1. \nThis is indicative of Runge's phenomenon, where higher-degree polynomials used for interpolation \n over an interval can lead to large oscillations and poor approximation outside the data points.")

#Q2)

import numpy as np
import matplotlib.pyplot as plt

# Standard normal distribution function
def f(x):
    return (1 / np.sqrt(2 * np.pi)) * np.exp(-0.5 * x**2)

# True value of P(Z < 2)
true_value = 0.977249868051821

a, b = -10, 2

# Trapezoidal rule implementation
def trapezoidal_rule(a, b, n):
    x = np.linspace(a, b, n)
    y = f(x)
    h = (b - a) / (n - 1)
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral, x, y

# Simpson's rule implementation
def simpsons_rule(a, b, n):
    if n % 2 == 0:
        n += 1  # Ensure odd number of points
    x = np.linspace(a, b, n)
    y = f(x)
    h = (b - a) / (n - 1)
    integral = (h / 3) * (y[0] + y[-1] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]))
    return integral, x, y

# Compute results for 2001 points
n1 = 2001
trap_result1, x_trap1, y_trap1 = trapezoidal_rule(a, b, n1)
simp_result1, x_simp1, y_simp1 = simpsons_rule(a, b, n1)

# Compute results for 4001 points
n2 = 4001
trap_result2, x_trap2, y_trap2 = trapezoidal_rule(a, b, n2)
simp_result2, x_simp2, y_simp2 = simpsons_rule(a, b, n2)

print(f"Trapezoidal Rule (2001 points): {trap_result1:.8f}")
print(f"Simpson's Rule (2001 points): {simp_result1:.8f}")
print(f"Trapezoidal Rule (4001 points): {trap_result2:.8f}")
print(f"Simpson's Rule (4001 points): {simp_result2:.8f}")

# Visualization
plt.figure(figsize=(15, 10))

# Plot 1: Function and Trapezoidal Approximation (2001 points)
plt.subplot(2, 2, 1)
plt.plot(x_trap1, y_trap1, label='f(x)', color='blue')
for i in range(len(x_trap1)-1):
    plt.fill_between([x_trap1[i], x_trap1[i+1]], [0, 0], [y_trap1[i], y_trap1[i+1]], color='lightgreen', alpha=0.3)
plt.title('Trapezoidal Rule Approximation (2001 points)')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()

# Plot 2: Function and Simpson's Approximation (2001 points)
plt.subplot(2, 2, 2)
plt.plot(x_simp1, y_simp1, label='f(x)', color='blue')
x_mid = (x_simp1[:-1] + x_simp1[1:]) / 2
y_mid = f(x_mid)
for i in range(0, len(x_simp1)-2, 2):
    plt.fill_between([x_simp1[i], x_simp1[i+2]], [0, 0], [y_simp1[i], y_simp1[i+2]], color='skyblue', alpha=0.3, interpolate=True)
plt.title("Simpson's Rule Approximation (2001 points)")
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()

# Plot 3: Function and Trapezoidal Approximation (4001 points)
plt.subplot(2, 2, 3)
plt.plot(x_trap2, y_trap2, label='f(x)', color='blue')
for i in range(len(x_trap2)-1):
    plt.fill_between([x_trap2[i], x_trap2[i+1]], [0, 0], [y_trap2[i], y_trap2[i+1]], color='lightgreen', alpha=0.3)
plt.title('Trapezoidal Rule Approximation (4001 points)')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()

# Plot 4: Function and Simpson's Approximation (4001 points)
plt.subplot(2, 2, 4)
plt.plot(x_simp2, y_simp2, label='f(x)', color='blue')
x_mid = (x_simp2[:-1] + x_simp2[1:]) / 2
y_mid = f(x_mid)
for i in range(0, len(x_simp2)-2, 2):
    plt.fill_between([x_simp2[i], x_simp2[i+2]], [0, 0], [y_simp2[i], y_simp2[i+2]], color='skyblue', alpha=0.3, interpolate=True)
plt.title("Simpson's Rule Approximation (4001 points)")
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()

plt.tight_layout()
plt.show()

# Convergence comment
print("\nConvergence behavior: Both the trapezoidal and Simpson's rules approximate the\n integral better with an increase from 2001 to 4001 points.\n Simpson's rule, being a higher-order method (O(h^4)),\n shows faster convergence and a closer approximation to the\n true value compared to the trapezoidal rule (O(h^2)), especially noticeable with the finer grid.")

#Q3)

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return np.sin(x)

exact_value = 1 - np.cos(5)  # ∫sin(x)dx from 0 to 5

# Composite Trapezoidal Rule
def composite_trapezoidal(a, b, n):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral, x, y

# Composite Simpson's Rule
def composite_simpsons(a, b, n):
    if n % 2 != 0:
        n += 1  # Ensure even number of subintervals
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 3) * (y[0] + y[-1] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]))
    return integral, x, y

a, b = 0, 5
n = 20        # Number of subintervals

# Computing integrals
trap_result, x_trap, y_trap = composite_trapezoidal(a, b, n)
simp_result, x_simp, y_simp = composite_simpsons(a, b, n)

# Computing absolute errors
trap_error = abs(exact_value - trap_result)
simp_error = abs(exact_value - simp_result)

# Printing results
print(f"Exact Value: {exact_value:.8f}")
print(f"Composite Trapezoidal Rule (20 subintervals): {trap_result:.8f}, Absolute Error: {trap_error:.8f}")
print(f"Composite Simpson's Rule (20 subintervals): {simp_result:.8f}, Absolute Error: {simp_error:.8f}")

# Visualization
plt.figure(figsize=(12, 5))

# Plot 1: Function and Trapezoidal Approximation
plt.subplot(1, 2, 1)
plt.plot(x_trap, y_trap, label='sin(x)', color='blue')
for i in range(len(x_trap)-1):
    plt.fill_between([x_trap[i], x_trap[i+1]], [0, 0], [y_trap[i], y_trap[i+1]], color='red', alpha=0.3)
plt.title('Composite Trapezoidal Rule (20 subintervals)')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.legend()

# Plot 2: Function and Simpson's Approximation
plt.subplot(1, 2, 2)
plt.plot(x_simp, y_simp, label='sin(x)', color='blue')
for i in range(0, len(x_simp)-2, 2):
    plt.fill_between([x_simp[i], x_simp[i+2]], [0, 0], [y_simp[i], y_simp[i+2]], color='green', alpha=0.3, interpolate=True)
plt.title("Composite Simpson's Rule (20 subintervals)")
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.legend()

plt.tight_layout()
plt.show()

# Convergence comment
print("\nComparison: The Composite Simpson's Rule provides a more accurate approximation than the Composite Trapezoidal Rule\n due to its higher order of accuracy (O(h^4) vs. O(h^2)).\n The absolute error for Simpson's rule is significantly lower, reflecting its better performance for this smooth function over 20 subintervals.")

#Q4)

import numpy as np
import matplotlib.pyplot as plt
from scipy import integrate

def f(x):
    return np.exp(-x**2)

# Exact value of the integral (approximated numerically since it's not elementary)
exact_value, _ = integrate.quad(f, 0, 1)

# Composite Trapezoidal Rule
def composite_trapezoidal(a, b, n):
    x = np.linspace(a, b, n + 1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral, x, y

# Parameters
a, b = 0, 1  # Integration limits
n1 = 100      # 100 subintervals
n2 = 200      # 200 subintervals

# Compute integrals
trap_result1, x_trap1, y_trap1 = composite_trapezoidal(a, b, n1)
trap_result2, x_trap2, y_trap2 = composite_trapezoidal(a, b, n2)

# Compute errors
error1 = abs(exact_value - trap_result1)
error2 = abs(exact_value - trap_result2)

# Print results
print(f"Exact Value (numerical): {exact_value:.10f}")
print(f"Trapezoidal Rule (100 subintervals): {trap_result1:.10f}, Absolute Error: {error1:.10f}")
print(f"Trapezoidal Rule (200 subintervals): {trap_result2:.10f}, Absolute Error: {error2:.10f}")

# Estimate order of accuracy
h1 = (b - a) / n1
h2 = (b - a) / n2
order = np.log(error2 / error1) / np.log(h2 / h1)
print(f"Estimated Order of Accuracy: {order:.4f} (Expected ~2 due to O(h^2))")

# Visualization
plt.figure(figsize=(12, 5))

# Plot 1: Function and Trapezoidal Approximation (100 subintervals)
plt.subplot(1, 2, 1)
plt.plot(x_trap1, y_trap1, label='e^(-x^2)', color='blue')
for i in range(len(x_trap1)-1):
    plt.fill_between([x_trap1[i], x_trap1[i+1]], [0, 0], [y_trap1[i], y_trap1[i+1]], color='lightblue', alpha=0.3)
plt.title('Composite Trapezoidal Rule (100 subintervals)')
plt.xlabel('x')
plt.ylabel('e^(-x^2)')
plt.legend()

# Plot 2: Function and Trapezoidal Approximation (200 subintervals)
plt.subplot(1, 2, 2)
plt.plot(x_trap2, y_trap2, label='e^(-x^2)', color='blue')
for i in range(len(x_trap2)-1):
    plt.fill_between([x_trap2[i], x_trap2[i+1]], [0, 0], [y_trap2[i], y_trap2[i+1]], color='lightblue', alpha=0.3)
plt.title('Composite Trapezoidal Rule (200 subintervals)')
plt.xlabel('x')
plt.ylabel('e^(-x^2)')
plt.legend()

plt.tight_layout()
plt.show()